version: '3.8'

services:
  app:
    build: .
    container_name: email-app
    restart: always
    env_file:
      - ./config/.env
    ports:
      - 587:587
      - 80:3000
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb
    container_name: email-db
    restart: always
    healthcheck:
      test: "/usr/bin/mariadb --user=email --password=email --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 10s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: email
      MYSQL_USER: email
      MYSQL_PASSWORD: email
    ports:
      - 3306:3306
    volumes:
      - email-db:/var/lib/mysql
  
  redis:
    image: redis
    container_name: email-redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - email-redis:/data

volumes:
  email-db:
  email-redis:
