version: "3"

tasks:
  config:
    cmds:
      - cp ./config/.env.sample ./config/.env
  build:
    cmds:
      - docker build -t email-app .
  run:
    cmds:
      - docker compose up
  test:
    cmds:
      - go test ./... -v
      - go vet ./...
      - gosec ./...
