version: "3"

tasks:
  config:
    cmds:
      - cp ./config/.env.sample ./config/.env
  build:
    cmds:
      - docker build -t email-service .
  run:
    cmds:
      - docker run -it --publish 8025:8025 email-service
  test:
    cmds:
      - go test ./... --timeout 5s
