name: email

services:
  api:
    build: .
    container_name: email-api
    image: email-api
    restart: always
    ports:
      - ${SMTP_PORT}:${SMTP_PORT}
      - ${API_PORT}:${API_PORT}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - email-api:/var/log
  
  app:
    build: ../app
    container_name: email-app
    image: email-app
    restart: always
    ports:
      - ${APP_PORT}:${APP_PORT}

  db:
    image: mariadb
    container_name: email-db
    restart: always
    healthcheck:
      test: "/usr/bin/mariadb --user=email --password=email --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 10s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: email
      MYSQL_USER: email
      MYSQL_PASSWORD: email
    volumes:
      - email-db:/var/lib/mysql
  
  redis:
    image: redis
    container_name: email-redis
    restart: always
    volumes:
      - email-redis:/data

volumes:
  email-api:
  email-db:
  email-redis:
