version: "3"

tasks:
  config:
    cmds:
      - cp .env.sample .env
      - cp ../app/src/env.sample.json ../app/src/env.json
      - cp ../mailserver/.env.sample ../mailserver/.env
      - mkdir -p ../mailserver/docker-data/dms/config
      - cp ../mailserver/config/postfix-main.cf.sample ../mailserver/docker-data/dms/config/postfix-main.cf
      - cp ../mailserver/config/postfix-virtual.cf.sample ../mailserver/docker-data/dms/config/postfix-virtual.cf
      - cp ../mailserver/config/postfix-aliases.cf.sample ../mailserver/docker-data/dms/config/postfix-aliases.cf
      - cp ../mailserver/config/user-patches.sh.sample ../mailserver/docker-data/dms/config/user-patches.sh
  build:
    cmds:
      - docker compose build
  run:
    cmds:
      - docker compose up -d
  modernize:
    cmds:
      - go run golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize@latest -test ./...
  modernize_fix:
    cmds:
      - go run golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize@latest -fix -test ./...
  test:
    cmds:
      - go test ./... -v
      - go vet ./...
  docs:
    cmds:
      - swag init -g cmd/main.go
