version: "3"

tasks:
  config:
    cmds:
      - cp .env.sample .env
  build:
    cmds:
      - docker compose build
  run:
    cmds:
      - docker compose up
  test:
    cmds:
      - go test ./... -v
      - go vet ./...
      - gosec ./...
  docs:
    cmds:
      - swag init -g cmd/main.go
